Add notification for closeAccount
terminal42/contao-notification_center pull request #286
Opened 2023-05-14 06:54 UTC by AlexanderWillner

We've already all required hooks and code for sending a notification when a member gets activated. This patch adds the same functionality for the `closeAccount` event.

This change was implemented and tested using `1.6.14`. For the pull request a diff was generated for `main`. A backport for `1.6.15` would be nice.

2023-05-14 09:22 UTC, fritzmg commented
> A backport for `1.6.15` would be nice.

I am pretty sure `terminal42/notification_center` uses semantic versioning. New feature would go into `1.8`. Why do you need it for `1.6`?

2023-05-14 09:25 UTC, fritzmg requested changes

2023-05-14 09:25 UTC, fritzmg commented on library/NotificationCenter/ContaoHelper.php
> +        $objMember = \MemberModel::findByPk($objMember);
```suggestion
        }

        $objMember = MemberModel::findByPk($objMember);
```

2023-05-14 09:25 UTC, fritzmg commented on languages/de/tl_nc_notification.xlf
> +
Translations are managed on [Transifex](https://explore.transifex.com/terminal42/notification_center/) - you only need to provide the English translations and remove the other languages.

2023-05-14 09:25 UTC, fritzmg commented on languages/de/tl_module.xlf
> +
Translations are managed on [Transifex](https://explore.transifex.com/terminal42/notification_center/) - you only need to provide the English translations and remove the other languages.

2023-05-14 09:25 UTC, fritzmg commented on dca/tl_module.php
> +$GLOBALS['TL_DCA']['tl_module']['fields']['nc_close_notification']['eval']['ncNotificationChoices']['registration'] = array('member_close');
```suggestion
$GLOBALS['TL_DCA']['tl_module']['fields']['nc_close_notification']['eval']['ncNotificationChoices']['registration'] = array('member_close');

```

2023-05-14 09:26 UTC, fritzmg commented
> > A backport for 1.6.15 would be nice.
>
> I am pretty sure terminal42/notification_center uses semantic versioning. New feature would go into 1.8. Why do you need it for 1.6?

Btw. the changes in this PR could easily be integrated as an App customisation or even extension of your own, if you really need it for an older feature version.

2023-05-14 10:01 UTC, AlexanderWillner commented
> > I am pretty sure terminal42/notification_center uses semantic versioning. New feature would go into 1.8. Why do you need it for 1.6?

As version 1.6 is needed for setups with Haste Version 4.*

> Btw. the changes in this PR could easily be integrated as an App customisation or even extension of your own, if you really need it for an older feature version.

We've many customisations, just trying to give changes back to the community.

2023-05-15 07:42 UTC, fritzmg approved these changes
lgtm in general :)

Two things to consider though:

The name of the new `member_close_mode` token does not make much sense to me. The `member_*` tokens are supposed to represent the properties of the member itself. However the `member_close_mode` represents the `reg_close` setting in the close account module. imho the token's name should be just `close_mode` for example.

The new token is also missing in the `$GLOBALS['NOTIFICATION_CENTER']['NOTIFICATION_TYPE']` array. It should be added to `email_subject`, `email_text` and `email_html` for the `member_close` notification type.

2023-05-15 10:25 UTC, fritzmg commented
👍 

The `tokens.xlf` still needs to be updated though with a description of thew new token.

2023-05-15 10:35 UTC, AlexanderWillner commented
Added a suggestion.

2023-05-15 10:52 UTC, fritzmg commented
Did you test this change? Doesn't it need to be `NOTIFICATION_CENTER_TOKEN.member_close.close_mode`?

2023-05-15 13:53 UTC, Toflar commented
Thanks for the contribution! However, I won't be releasing any new 1.x version anymore. Even if I did, it would not be helpful to you as it would have to be 1.8 and thus haste 5-only anyway - I don't want to backport anything and release as bugfix release and potentially causing other issues unless it's absolutely necessary (which a new feature does not qualify for).

I would love to see the PR being picked up again after v2 is released, though. Maybe it can be a nice addition to the core then and be part of a future 2.1 or 2.x release? :) 

In the meantime, feel free to publish this as your own extension which allows you to meet all your needs.

2024-02-01 15:51 UTC, Toflar commented
I'm cleaning up issues and PRs so I will have to close this PR but please, feel free to work on a PR for version 2 (to be released very, very soon) once it's here if you still care 😊

2024-02-01 15:51 UTC, closed without merging